### ISSUE TITLE
Possible features to implement

### ISSUE THREAD

**Issue by felipebravom** [Waikato/wekaDeeplearning4j#13]
I think it would a good idea to have CNN and RNN classifiers that can act directly on string attributes so as SGDText : http://weka.sourceforge.net/doc.dev/weka/classifiers/functions/SGDText.html

These classifiers should receive pre-trained word embeddings as parameters. 
The following two dl4j examples should help:

https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/sentenceclassification/CnnSentenceClassificationExample.java

https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/word2vecsentiment/Word2VecSentimentRNN.java

**Comment by slang03** [comment]
[Word2VecSentimentRNN](https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/word2vecsentiment/Word2VecSentimentRNN.java) functionality will be available with v1.4.0

CNN text classification will be available soon as well.
