### ISSUE TITLE
NaN default parameters

### ISSUE THREAD

**Issue by felipebravom** [Waikato/wekaDeeplearning4j#17]
Hi,
I'm finding the default values of many parameters as NaN (e.g., Convolution Layer, NeuralNet Configuration). 
The FileIterationListener is raising an exception.

Cheers,
Felipe

**Comment by slang03** [comment]
The actual default parameters are not `NaN` but set as default parameters used in the dl4j backend. I just need to update the descriptions. Many of those parameters will vanish with the next version of dl4j anyway and it will be more clear which parameters are available for which object.

> The FileIterationListener is raising an exception.

Could you provide me with a log of this exception?

**Comment by felipebravom** [comment]
Thanks. I'm getting a Class load failed message in the GUI and the following stack trace:
I'm getting a java.lang.InstantiationException: weka.dl4j.listener.FileIterationListener
	java.lang.Class.newInstance(Class.java:427)
	weka.gui.GenericObjectEditor.classSelected(GenericObjectEditor.java:1865)
	weka.gui.GenericObjectEditor$3.valueChanged(GenericObjectEditor.java:1743)
	javax.swing.JTree.fireValueChanged(JTree.java:2927)
	javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3391)

**Comment by slang03** [comment]
> The actual default parameters are not NaN but set as default parameters used in the dl4j backend.
I have to correct that: the backend is using the `NaN` value as a flag to indicate that this property should not be used. As soon as it is set to some value which is not `NaN`, the parameter will be used.
