### ISSUE TITLE
Deeplearning4j API upgrade 1.0.0

### ISSUE THREAD

**Issue by steven-lang** [Waikato/wekaDeeplearning4j#29]
### Description

Fully upgrade the Deeplearning4j API to version 1.0.0. See also [1.0.0-alpha release-notes](https://deeplearning4j.org/releasenotes)

**Comment by slang03** [comment]
As of this package's version `1.5.0` the Deeplearning4j `1.0.0-beta` API is covered. More changes are coming in the transition from `1.0.0-beta` to `1.0.0`
