### ISSUE TITLE
Cant install wekaDeeplearning4j

### ISSUE THREAD

**Issue by chanapong3** [Waikato/wekaDeeplearning4j#33]
### Description
Cant install wekaDeeplearning4j  when I looked at console when start weka 3.8 console show like this

Skipping package wekaDeeplearning4j the OS/arch (Windows 7 x86) does not meet package OS/arch constraints:  64   

It is look like wrong version 32 and 64 bit.
I use this file wekaDeeplearning4j-1.5.3.zip
How can I fix this issued ?
Sorry if i did something wrong I am newbie here.

### Additional Information

- Weka version:
- wekaDeeplearning4j package version: 1.5.3
- Operating System: win7 64

**Comment by chanapong3** [comment]
Hello The problem is gone.
1.But I got new problems. When I run Dl4j classifier.
it is show like this " Problem evaluating classifier: NULL "
2.How I know my WEKA is running in GPU base ?
Thank a lot for fast response.

**Comment by steven-lang** [comment]
1. Could you please elaborate the steps you have taken that lead to "Problem evaluating classifier: NULL"?
2. Did you install the CUDA libraries? If not, check out our [guide](https://deeplearning.cms.waikato.ac.nz/install#add-gpu-support).

**Comment by chanapong3** [comment]
1) I added my data set to WEKA.
1.1)    I click classifies TAB and then Click Start to build model with Default Parameters. (Dlj4 classifier)
1.2)Then the dialog was pop up.  " Problem evaluating classifier: NULL "

2)I have CUDA libraries already(was use with tensorflow).
But i dont understand this line of code.

 ./install-cuda.sh ~/Downloads/wekaDeeplearning4j-cuda-9.1-1.5.0-linux-x86_64.zip  

i tried to change to my file PATH. But it doesn't work.
my cmd show like this
The term 'install-cuda-libs.ps1' is not recognized as the name of a cmdlet,fuction,script file

**Comment by steven-lang** [comment]
1) Would you mind sharing that dataset so I can have a look at what goes wrong? 
2) You can just start the `install-cuda-libs.sh` powershell script and it automatically downloads and installs the additional libraries that are necessary for the package to use the GPU. You can [download](https://github.com/Waikato/wekaDeeplearning4j/releases/download/v1.5.3/install-cuda-libs.ps1) it from the latest release.

**Comment by chanapong3** [comment]
1.I used Iris data set still have the same problems.
2. Now I can install CUDA !!! my computer block script for security reason !!
3.Why my WEKA main directory is not WEKA_HOME(That have wekafiles fodler in it)

**Comment by chanapong3** [comment]
weka.classifiers.functions.Dl4jMlpClassifier.buildClassifier(Dl4jMlpClas
sifier.java:682)
        weka.gui.explorer.ClassifierPanel$18.run(ClassifierPanel.java:1456)

        at org.nd4j.linalg.factory.Nd4j.zeros(Nd4j.java:5441)
        at weka.classifiers.functions.dl4j.Utils.instancesToDataSet(Utils.java:6
1)
        at weka.dl4j.iterators.instance.DefaultInstanceIterator.getDataSetIterat
or(DefaultInstanceIterator.java:67)
        at weka.dl4j.iterators.instance.AbstractInstanceIterator.getDataSetItera
tor(AbstractInstanceIterator.java:58)
        at weka.classifiers.functions.Dl4jMlpClassifier.getDataSetIterator(Dl4jM
lpClassifier.java:829)
        at weka.classifiers.functions.Dl4jMlpClassifier.getDataSetIterator(Dl4jM
lpClassifier.java:865)
        at weka.classifiers.functions.Dl4jMlpClassifier.getFirstBatchFeatures(Dl
4jMlpClassifier.java:1200)
        at weka.classifiers.functions.Dl4jMlpClassifier.createModel(Dl4jMlpClass
ifier.java:1036)
        at weka.classifiers.functions.Dl4jMlpClassifier.initializeClassifier(Dl4
jMlpClassifier.java:745)
        at weka.classifiers.functions.Dl4jMlpClassifier.buildClassifier(Dl4jMlpC
lassifier.java:682)
        at weka.gui.explorer.ClassifierPanel$18.run(ClassifierPanel.java:1456)



This happen when I start to build model with Iris data

**Comment by steven-lang** [comment]
Which Weka version do you use?

**Comment by chanapong3** [comment]
3.8.2

**Comment by steven-lang** [comment]
When seeing the error above, could you please scroll up and check for any sophisticated error message? I have the feeling that you either have a 32 bit Java installation or your Windows is 32 bit. Please [check](https://support.microsoft.com/en-us/help/827218/how-to-determine-whether-a-computer-is-running-a-32-bit-version-or-64) that as well.

**Comment by chanapong3** [comment]
It is work !! 
My window is 64 bit .My java is 64 bit too.
I reinstall my JAVA and it s work. 
Thanks a lot.
Now it is time to play  WEKA.
PS.How to know my WEKA is run on GPU.

**Comment by eibe** [comment]
You can use the nvidia-smi command to check what processes are running on the GPU.

**Comment by steven-lang** [comment]
Nice to hear. 

You can either check the console output when starting the classifier it should give some message that JCuBlas has been loaded and that your Graphic card with a certain amount of memory has been found.

On the other side you can also check your GPU stats with GPU-Z.

**Comment by chanapong3** [comment]
Thank a lot.

**Comment by Cknnne** [comment]
I have the same problem while adding GPU support :(
After entering"./install-cuda-libs.ps1~/ "C:\Users\USER\Downloads\wekaDeeplearning4j-cuda-8.0-1.5.13-windows-x86_64.zip"
my cmd shows this"bash: ./install-cuda-libs.ps1~/: No such file or directory"

![image](https://user-images.githubusercontent.com/39508332/64485207-1c911e80-d250-11e9-8e90-8aad46e5652f.png)

### **Additional Information**

- Weka version:3.83
- wekaDeeplearning4j package version: 1.5.13
- CUDA version: 8.0
- Operating System: win10 64

**Comment by chanapong3** [comment]
Did you check file is in there ?
Or about  " \" change to this "/"
I am not professional.


________________________________

**Comment by GeethaSushama123** [comment]
I have weka 3.8.5 . I tried to install wekaDeeplearning4j:1.7.2 through GUI of weka Package Manager. Showing that it is installed. But when GPU is checked using "Is GPU Avaliable" showing false. I have cuda version showing 11.0 by " nvcc-V" command and  Driver Version: 512.15       CUDA Version: 11.6 by "nvdia-smi" command. what should i do to get the GPU available for wekaDeeplearning4j

**Comment by eibe** [comment]
The current version of wekaDeeplearning4j requires CUDA Toolkit 10.0, 10.1,
or 10.2, so you will need to use 10.2 instead of a later version.
