### ISSUE TITLE
Problem evaluating forecaster

### ISSUE THREAD

**Issue by lumio83** [Waikato/wekaDeeplearning4j#36]
When using wekadeeplearning4j for time series forecast, and setting up LSTM layer and Rnnoutputlayer I get this message:
Problem evaluating forecaster
indexes must be same length as array rank.

What could be the problem here ?

- Weka version: 3.8.2
- wekaDeeplearning4j package version: 1.5.6
- Operating System: linux

**Comment by steven-lang** [comment]
Hi lumio83,

which class are you using? `RnnSequenceClassifier`?
Are you using the Weka GUI or did you write a java program? 
If it is the second, could you provide your code snippet and the stack trace?
If you are using the GUI, could you provide the configuration of your setup?

**Comment by lumio83** [comment]
Hi
I am using Weka GUI with dl4jmlp classifier for time series forecast. In layers just one LSTM layer + rnnoutput layer.

**Comment by steven-lang** [comment]
Time series forecasting is currently not supported but rather WIP [here](https://github.com/steven-lang/weka-rnn-forecaster). The `RnnForecaster` (when ready) will be what you are looking for.
