### ISSUE TITLE
View dl4j debug logs

### ISSUE THREAD

**Issue by sarda014** [Waikato/wekaDeeplearning4j#39]
**Is your feature request related to a problem? Please describe.**
I am using wekaDeeplearning4j through weka UI. After setting the debug option to True, I do not see any additional logs in weka.log or network.log 

**Describe the solution you'd like**
dl4j also provides debug logs, it would be helpful if we can view dl4j logs when the debug option is set to true.

**Comment by steven-lang** [comment]
Could you elaborate which logs from dl4j you mean? The general dl4j logs that are generated when running dl4j code?

Currently, `weka.log` contains the logs with weka specific messages while `network.log` only contains output from the `EpochListener`. This is definitely something we should improve/make more clear.

As of now,  dl4j logs are only printed to STDOUT (which is the terminal if you start weka from the there) and these are filtered to only show "warning" logs ([see the log4j2.xml config file](https://github.com/Waikato/wekaDeeplearning4j/blob/master/src/main/resources/log4j2.xml#L12)).

**Comment by steven-lang** [comment]
I've implemented a log configuration available in the `Dl4jMlpClassifier` which will be released with v1.5.8 soon.

This allows you to set the log level of the `Nd4j` backend, the `Dl4j` framework and `WekaDl4j` separately:

![](https://i.imgur.com/5wncpxv.png)
