### ISSUE TITLE
Installation instructions are incorrect. (How about the GUI starting instructions?)

### ISSUE THREAD

**Issue by shyamalschandra** [Waikato/wekaDeeplearning4j#40]
**Describe the bug**
Installation instructions are incorrect for release version on Github and the website.

**To Reproduce**
Installation instructions are incorrect.

**Expected behavior**
What are the right installation instructions for Weka for Deep Learning?

**Additional Information**

- Weka version 1.5.8
- wekaDeeplearning4j package version:
- Operating System: MacOS Mojave

**Additional context**

**Comment by steven-lang** [comment]
At which step does your installation fail?

You can simply install the package via the Weka PackageManager.

Please attach any errors you get.

**Comment by steven-lang** [comment]
Closed due to no response.
