### ISSUE TITLE
Add Cuda 10 support

### ISSUE THREAD

**Issue by mansueli** [Waikato/wekaDeeplearning4j#54]
The add-gpu-support page (https://deeplearning.cms.waikato.ac.nz/install/#add-gpu-support) specifies that one need cuda v8 or cuda v9.  Please add support for cuda v10.x

**Comment by steven-lang** [comment]
Deeplearning4j has added [Cuda 10.0 support](https://deeplearning4j.org/release-notes) in v1.0.0-beta3. We are currently using v1.0.0-beta2 as backend which only supports Cuda version up to 9.2. When we update the package to the next Deeplearning4j version (hopefully v1.0.0 stable at some point), Cuda 10.0 will be supported.

**Comment by mansueli** [comment]
I thought that I've added this as a feature request. I know support just got to their beta version. 
This was more a broad request to let you guys know we do want to use the last cuda version than anything. 

Thanks for the quick reply here!

**Comment by Yasirkhan96** [comment]
HI Guys !! i installed weka and visual studio  2015 but i cant install cuda why?
and also how we can link GPU with weka kindlu guide me.

**Comment by steven-lang** [comment]
Cuda 10 support has been added in 1.5.14.

@Yasirkhan96 Please file a new issue and be more specific about your setup - thanks.

**Comment by Yasirkhan96** [comment]
Actually I am having problem with installing Cuda and I am unable to
connect gpu with weka.

**Comment by steven-lang** [comment]
Again, please be more specific about your setup:

What are you trying to do?
Which cuda version?
Which OS?
Which Weka version?

List the steps that you have taken.

If you have issues installing Cuda, please refer to the appropriate official nvidia installation guides: https://docs.nvidia.com/cuda/index.html
