### ISSUE TITLE
how to apply 1-d convolution?

### ISSUE THREAD

**Issue by hahakid** [Waikato/wekaDeeplearning4j#55]
I tried to change the filter with 3*1 but the input is error

**Comment by eibe** [comment]
That should work. What was the exact error? Are you sure the stride parameter, etc., were consistent with the format of your input data?

**Comment by hahakid** [comment]
@eibe I will try it later, maybe caused by input error. feedforward input not conv input, something like that.

**Comment by steven-lang** [comment]
Keep in mind that you need a dataset iterator that supports convolutions. If you share exact error with us we may be able to help you further.

Check out https://deeplearning.cms.waikato.ac.nz/user-guide/data/ for help on dataset iterators and https://deeplearning.cms.waikato.ac.nz/examples/classifying-mnist/ for an example on the MNIST dataset.

**Comment by steven-lang** [comment]
Since there is no further response, I will close this issue.
