### ISSUE TITLE
after installed, it shows could not find wekadeeplearning4j?

### ISSUE THREAD

**Issue by qq2898** [Waikato/wekaDeeplearning4j#57]
it is not a bug, but i meet it ...
Hello,
after I installed wekadeeplearning4j, I test it with the result
Installed   Repository  Loaded  Package
=========   ==========  ======  =======
1.5.14       -----       Yes     <PACKAGE>: Weka wrappers for Deeplearning4j

but when I run the 
./install-cuda-libs.ps1 ~/Downloads/wekaDeeplearning4j-cuda-10.1-1.5.14-windows-x86_64.zip
or 
./install-cuda-libs.ps1
it shows Could not fine users\admin\wekafiles\packages\wekaDeeplearning4j, but it really exists.
How TO DO?  THANK YOU

**Comment by steven-lang** [comment]
What is the value of your `WEKA_HOME` environment variable?

According to your path, you are running it as administrator, is that where you have installed Weka?

**Comment by qq2898** [comment]
I find there is no WEKA_HOME environment variable so I just added it, WEKA_HOME="C:\Program Files\Weka-3-8", but it still says could not find wekadeeplearning4j as same.
"admin" is my user account which i created and used, I installed WEKA in C:\Program Files\Weka-3-8.


------------------ 原始邮件 ------------------
发件人: "Steven Lang"<notifications@github.com>;
发送时间: 2019年10月14日(星期一) 下午2:06
收件人: "Waikato/wekaDeeplearning4j"<wekaDeeplearning4j@noreply.github.com>;
抄送: "Gao Lei"<28987240@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Waikato/wekaDeeplearning4j] after installed, it shows could notfind wekadeeplearning4j? (#57)




What is the value of your WEKA_HOME environment variable?
 
According to your path, you are running it as administrator, is that where you have installed Weka?

**Comment by steven-lang** [comment]
Can you please try setting the `WEKA_HOME` variable to `C:\Users\admin\wekafiles`?

**Comment by qq2898** [comment]
thank you, it runs well



---Original---

**Comment by steven-lang** [comment]
Nice. I have to check the installation script for Windows again. Something seems to be not working right. Thanks for reporting!
