### ISSUE TITLE
Latest CUDA version is 11.1

### ISSUE THREAD

**Issue by celestinoxp** [Waikato/wekaDeeplearning4j#64]
Latest wekaDeeplearning4j package not supports latest CUDA package?

when try execute install-cuda-libs.ps1 show error msg: "Could not detect CUDA version. Is CUDA installed?"

I'm using Windows 10 64 bits and I have latest CUDA package (is 11.1)

**Comment by basedrhys** [comment]
Hi,

Unfortunately, Deeplearning4j (the backend this package uses) only supports up to CUDA 10.2 at this time. They should bring out support for later CUDA versions in the next release.

**Comment by celestinoxp** [comment]
Nvidia is announcing CUDA 11.5:
https://developer.nvidia.com/blog/revealing-new-features-in-the-cuda-11-5-toolkit/

Question:  what appens if "wekaDeeplearning4j" updates to latest vesion of CUDA?
