### ISSUE TITLE
wekaDeeplearning4j i386

### ISSUE THREAD

**Issue by raul-parada** [Waikato/wekaDeeplearning4j#65]
**Is your feature request related to a problem? Please describe.**
I cannot install the package in Weka i386 (32 bits). 

**Describe the solution you'd like**
Adapt the library to OS/Arc (i386)

**Describe alternatives you've considered**
None

**Additional context**

**Comment by basedrhys** [comment]
Hi, thanks for trying out WekaDeeplearning4j. Unfortunately, Deeplearning4j (the backend this package is a wrapper for) doesn't support the i386 intel architecture and so WekaDeeplearning4j also won't be supporting it.

Apologies for the inconvenience.
