### ISSUE TITLE
Unable to change NGramTokenizerFactory properties (GUI)

### ISSUE THREAD

**Issue by fdebeyan** [Waikato/wekaDeeplearning4j#66]
### Description
In DJ4LStringToWordVec, using NGramTokenizerFactory, when I click on properties and change NMax, NMin or delimiters and click on OK, the properties are not changed.

#### Expected behavior:
Properties (NMax, NMin, Delimiters) are changed.

#### Encountered behavior:
Properties (NMax, NMin, Delimiters) revert to default values.

### Additional Information

- Weka version: 3.8.5
- wekaDeeplearning4j package version: 1.7.1
- Operating System: Mac and Linux.

**Comment by basedrhys** [comment]
Thanks for finding this - will look into it.

**Comment by basedrhys** [comment]
Have fixed this issue - will be included in the next WDL4J minor release (coming soon)
